import React from 'react';
import { AppProvider, useApp } from './context/AppContext';
import { ToastProvider } from './context/ToastContext';
import { Header } from './components/layout/Header';
import { TorrentInput } from './components/features/TorrentInput';
import { TaskList } from './components/features/TaskList';

function CloudLeecherApp() {
  const { apiUrl, isConnected } = useApp();

  return (
    <div className="min-h-screen text-white selection:bg-white/30 flex flex-col overflow-x-hidden max-w-full">
      <Header />

      <main className="max-w-4xl mx-auto px-4 py-8 flex-1 w-full overflow-hidden">
        {!apiUrl ? (
          <div className="text-center py-20 animate-fade-in">
            <h2 className="text-2xl font-bold mb-4">Welcome to CloudLeecher</h2>
            <p className="text-gray-400 max-w-md mx-auto mb-8">
              To get started, please paste the <strong>Public URL</strong> generated by your Google Colab notebook in the settings header above.
            </p>
            <div className="p-4 bg-surface rounded-lg border border-dashed border-white/10 inline-block text-left text-sm text-gray-500">
              <p>1. Run the Notebook</p>
              <p>2. Copy the Ngrok URL (e.g., https://...ngrok-free.app)</p>
              <p>3. Click the <span className="inline-block p-1 bg-white/10 rounded mx-1">Settings</span> icon above</p>
              <p>4. Paste and Connect</p>
            </div>
          </div>
        ) : (
          <div className="animate-slide-up">
            {/* Only show input if connected, or maybe allow queuing? Backend needed for add. */}
            {isConnected ? (
              <TorrentInput />
            ) : (
              <div className="bg-warning/10 border border-warning/20 text-warning p-4 rounded-xl mb-8 flex items-center justify-between">
                <span>⚠️ Backend Check Failed. Changes may not be saved. check your Colab tab.</span>
              </div>
            )}
            <TaskList />
          </div>
        )}
      </main>

      <footer className="py-6 text-center text-xs text-gray-600 border-t border-white/5 bg-black/40 backdrop-blur-sm">
        <div className="max-w-4xl mx-auto px-4 space-y-3">
          <div className="flex flex-row items-center justify-center gap-4">
            <a
              href="https://github.com/heavens7above"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 text-gray-500 hover:text-white transition-colors"
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
              </svg>
              GitHub
            </a>
            <span className="text-gray-700">•</span>
            <button
              onClick={() => {
                navigator.clipboard.writeText('bc1qax02dgg0f7gj4c0p7986rv3dw7nfd5zt4ydldc');
                alert('Bitcoin address copied to clipboard!');
              }}
              className="flex items-center gap-1.5 text-gray-500 hover:text-orange-400 transition-colors"
              title="Click to copy Bitcoin address"
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M23.638 14.904c-1.602 6.43-8.113 10.34-14.542 8.736C2.67 22.05-1.244 15.525.362 9.105 1.962 2.67 8.475-1.243 14.9.358c6.43 1.605 10.342 8.115 8.738 14.548v-.002zm-6.35-4.613c.24-1.59-.974-2.45-2.64-3.03l.54-2.153-1.315-.33-.525 2.107c-.345-.087-.705-.167-1.064-.25l.526-2.127-1.32-.33-.54 2.165c-.285-.067-.565-.132-.84-.2l-1.815-.45-.35 1.407s.975.225.955.236c.535.136.63.486.615.766l-1.477 5.92c-.075.166-.24.406-.614.314.015.02-.96-.24-.96-.24l-.66 1.51 1.71.426.93.242-.54 2.19 1.32.327.54-2.17c.36.1.705.19 1.05.273l-.51 2.154 1.32.33.545-2.19c2.24.427 3.93.257 4.64-1.774.57-1.637-.03-2.58-1.217-3.196.854-.193 1.5-.76 1.68-1.93h.01zm-3.01 4.22c-.404 1.64-3.157.75-4.05.53l.72-2.9c.896.23 3.757.67 3.33 2.37zm.41-4.24c-.37 1.49-2.662.735-3.405.55l.654-2.64c.744.18 3.137.524 2.75 2.084v.006z" />
              </svg>
              Donate BTC
            </button>
          </div>
          <p className="text-gray-700">© 2026 CloudLeecher Project. Created by Sam.</p>
        </div>
      </footer>
    </div>
  );
}

function App() {
  return (
    <ToastProvider>
      <AppProvider>
        <CloudLeecherApp />
      </AppProvider>
    </ToastProvider>
  );
}

export default App;
